
#include "rules.h"

#include "debug.h"

#include "util.h"



const char* LANG_ELEMENTS[] =
{
    "lisp-char ::=",
    "whitespace ::=",
    "backspace ::=",
    "tab ::=",
    "newline ::=",
    "linefeed ::=",
    "page ::=",
    "return-char ::=",
    "space ::=",
    "constituent-char ::=",
    "rubout ::=",
    "single-escape ::=",
    "multiple-escape ::=",
    "macro-char ::=",
    "terminating-char ::=",
    "non-terminating-char ::=",
    "token ::=",
    "number-token ::=",
    "integer ::=",
    "ratio ::=",
    "float ::=",
    "exponent ::=",
    "sign ::=",
    "slash ::=",
    "decimal-point ::=",
    "exponent-marker ::=",
    "decimal-digit ::=",
    "digit ::=",
    "symbol-token ::=",
    "list ::=",
    "object ::=",
    "element ::=",
    "list_car_element ::=",
    "cons ::=",
    "car ::=",
    "cdr ::=",
    "setq ::=",
    "setq-pair ::=",
    "setq-var ::=",
    "defconstant ::=",
    "name ::=",
    "form ::=",
    "documentation ::=",
    "compound-form ::=",
    "operator ::=",
    "function-call-operator ::=",
    "special-form-operator ::=",
    "macro-operator ::=",
    "string ::=",
    "if ::=",
    "test-form ::=",
    "then-form ::=",
    "else-form ::=",
    "eq ::=",
    "eql ::=",
    "equal ::=",
    "loop ::=",
    "return ::=",
    "block ::=",
    "block-name ::=",
    "defun ::=",
    "function-name ::=",
    "lambda-list ::=",
    "declaration ::=",
    "expression ::=",
    "let ::=",
    "var ::=",
    "init-form ::=",
    "num-add ::=",
    "num-less-than ::=",
    "num-less-or-equal-than ::=",
    "num-greater-than ::=",
    "num-greater-or-equal-than ::=",
    "num-equal-than ::=",
    "num-not-equal-than ::=",

    "defstruct ::=",
    "slot-name ::=",
    "defmacro ::=",
    "[sign]",
    "{decimal-digit}",
    "{digit}",
    "[exponent]",
    "[decimal-point {decimal-digit}*]",
    "{number-token}",
    "num-euqal-than ::=",
    "{ object }",
    "{setq-pair}",
    "[else-form]",
    "[form]",
    "{ form }",
    "{compound-form}",
    "[documentation]",
    "{var}",
    "{form}",
    "{slot-name}",


    /* chars and keywords
     */
    "$",
    "%",
    "&",
    "*",
    "+",
    "-",
    ".",
    "/",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    ":",
    "<",
    "=",
    ">",
    "@",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "^",
    "_",
    "~",
    "#\rubout",
    "\"",
    "\'",
    "(",
    ")",
    ",",
    ";",
    "`",
    "##",
    "#\backslash",
    "#\vertical-bar",
    "#\b",
    "#\t",
    "#\r",
    "#\n",
    "#\\p",
    "#\\space",
    "left-parent",
    "right-parent",
    "##left-parent",
    ":=",
    "#\()right-parent",
    ":=",
    "#\\)",
    "<undefined>",
    "LIST",
    "array",
    "sequence",
    "type",
    "input-stream",
    "output-stream",
    "class",
    "CONS",
    "CAR",
    "CDR",
    "SETQ",
    "DEFCONSTANT",
    "SETQ",
    "LOOP",
    "lambda-expression",
    "<TBD>",
    "QUOTE",
    "LET",
    "LET*",
    "IF",
    "BLOCK",
    "CATCH",
    "THROW",
    "IF",
    "EQ",
    "(EQL",
    "(EQUAL",
    "LOOP",
    "RETURN",
    "BLOCK",
    "DEFUN",
    "LET",
    "(var",
    "(var",
    "init-form))",
    "<=",
    ">=",
    "/=",
    "!=",
    "DEFSTRUCT",



    /* node's name
     */
    "token ::=",
    "	number-token | 	symbol-token 	",
    "<tmp>",
    "number-token ::=",
    "	integer | 	ratio | 	float 				          ",
    "integer ::=",
    "	[sign] {decimal-digit}+ decimal-point | 	[sign] {digit}+ 				         ",
    "[sign]",
    "sign",
    "sign ::=",
    "+ | -",
    "+",
    "-",
    "@",
    "{decimal-digit}",
    "{digit}",
    "ratio ::=",
    "	[sign] {digit}+ slash {digit}+  				      ",
    "float ::=",
    "	[sign] {decimal-digit}* decimal-point {decimal-digit}+ [exponent] |                        [sign] {decimal-digit}+ [decimal-point {decimal-digit}*] exponent 				       ",
    "symbol-token ::=",
    "<undefined>",
    "object ::=",
    "	element | 	<undefined> 	",
    "<tmp>",
    "element ::=",
    "	list_car_element | 	array | 	sequence | 	type | 	input-stream | 	output-stream | 	class 	",
    "list_car_element ::=",
    "	token | 	lisp-char 	",
    "token ::=",
    "lisp-char ::=",
    "	whitespace |  	constituent-char | 	single-escape |  	multiple-escape | 	macro-char 	",
    "whitespace ::=",
    "	backspace |  	tab |  	newline |  	linefeed |  	page |  	return-char |  	space 		",
    "backspace ::=",
    "#\b",
    "tab ::=",
    "#\t",
    "newline ::=",
    "#\r",
    "linefeed ::=",
    "#\n",
    "page ::=",
    "#\\p",
    "return-char ::=",
    "space ::=",
    "#\\space ",
    "#\\space",
    "constituent-char ::=",
    "	$ | % | & | * | + | - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout 	",
    "$",
    "%",
    "&",
    "*",
    "+",
    "-",
    ".",
    "/",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    ":",
    "<",
    "=",
    ">",
    "@",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "^",
    "_",
    "~",
    "rubout ::=",
    "#\rubout",
    "single-escape ::=",
    "#\backslash",
    "multiple-escape ::=",
    "#\vertical-bar",
    "macro-char ::=",
    "	terminating-char |  	non-terminating-char 	",
    "terminating-char ::=",
    "\" | ' | left-parent | right-parent | , | ; | `",
    "\"",
    "'",
    ",",
    ";",
    "`",
    "non-terminating-char ::=",
    "##  left-parent := #\() right-parent := #\\)",
    "list ::=",
    "	( LIST { object }* )",
    "(",
    "<tmp>",
    "cdr ::=",
    "( CDR list )",
    "(",
    "<tmp>",
    "num-not-equal-than ::=",
    "	( /= {number-token}* ) | 	( != {number-token}* )		 	 	",
    "<tmp>",
    "(",
    "equal ::=",
    "(EQUAL object object )",
    "compound-form ::=",
    "	list | 	car | 	cdr | 	cons | 	eq | 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* ) 	",
    "<tmp>",
    "list ::=",
    "car ::=",
    "cdr ::=",
    "cons ::=",
    "( CONS object object )",
    "(",
    "eq ::=",
    "if ::=",
    "	( IF test-form then-form [else-form] )",
    "return ::=",
    "	( RETURN [form] ) 	 	",
    "block ::=",
    "	( BLOCK block-name { form }* ) 	",
    "num-add ::=",
    "num-less-than ::=",
    "num-less-or-equal-than ::=",
    "num-greater-than ::=",
    "num-greater-or-equal-than ::=",
    "num-equal-than ::=",
    "	( = {number-token}* ) 			",
    "=",
    "{number-token}",
    "num-not-equal-than ::=",
    "setq ::=",
    "( SETQ {setq-pair}* )",
    "(",
    "<tmp>",
    "defconstant ::=",
    "( DEFCONSTANT name form [documentation] )",
    "(",
    "<tmp>",
    "if ::=",
    "	( IF test-form then-form [else-form] )",
    "(",
    "<tmp>",
    "return ::=",
    "	( RETURN [form] ) 	 	",
    "(",
    "<tmp>",
    "loop ::=",
    "	( LOOP {compound-form}* )",
    "(",
    "<tmp>",
    "defun ::=",
    "	( DEFUN function-name lambda-list [documentation] {form}* )",
    "(",
    "<tmp>",
    "defstruct ::=",
    "	( DEFSTRUCT name ( {slot-name}* ) ) 	",
    "(",
    "<tmp>",
    "defmacro ::=",
    "	( name lambda-list [documentation] {form}* ) 	 	 	",
    "(",
    "<tmp>",
    "name ::=",
    "<sub>",
    "symbol-token ::=",
    "lambda-list ::=",
    "{var}",
    "[documentation]",
    "documentation",
    "documentation ::=",
    "string",
    "string ::=",
    "<TBD>",
    "{form}",
    "@",
    
/* keys
 */
    "number-token",
    "integer",
    "[sign] {decimal-digit}+ decimal-point",
    "| -",
    " {decimal-digit}+ decimal-point",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " decimal-point",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " decimal-point",
    "| 	[sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "| 	ratio | 	float",
    "ratio",
    "| -",
    " {digit}+ slash {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    " slash {digit}+",
    "slash",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    " slash {digit}+",
    "slash",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "| 	float",
    "[sign] {decimal-digit}* decimal-point {decimal-digit}+ [exponent]",
    "| -",
    " {decimal-digit}* decimal-point {decimal-digit}+ [exponent]",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " decimal-point {decimal-digit}+ [exponent]",
    "decimal-point",
    " {decimal-digit}+ [exponent]",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " [exponent]",
    "exponent",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " decimal-point {decimal-digit}+ [exponent]",
    "decimal-point",
    " {decimal-digit}+ [exponent]",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " [exponent]",
    "exponent",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "|                        [sign] {decimal-digit}+ [decimal-point {decimal-digit}*] exponent",
    "| -",
    " {decimal-digit}+ [decimal-point {decimal-digit}*] exponent",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " [decimal-point {decimal-digit}*] exponent",
    "decimal-point {decimal-digit}*",
    "decimal-point",
    " {decimal-digit}*",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " exponent",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " [decimal-point {decimal-digit}*] exponent",
    "decimal-point {decimal-digit}*",
    "decimal-point",
    " {decimal-digit}*",
    "decimal-digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9",
    "| 4 | 5 | 6 | 7 | 8 | 9",
    "| 5 | 6 | 7 | 8 | 9",
    "| 6 | 7 | 8 | 9",
    "| 7 | 8 | 9",
    "| 8 | 9",
    "| 9",
    " exponent",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "	exponent-marker [sign] {digit}+	      ",
    "exponent-marker",
    "	e | s | f | d | l | E | S | F | D | L",
    "| s | f | d | l | E | S | F | D | L",
    "| f | d | l | E | S | F | D | L",
    "| d | l | E | S | F | D | L",
    "| l | E | S | F | D | L",
    "| E | S | F | D | L",
    "| S | F | D | L",
    "| F | D | L",
    "| D | L",
    "| L",
    " [sign] {digit}+",
    "| -",
    " {digit}+",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "digit",
    "0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined> 	",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 4 | 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 5 | 6 | 7 | 8 | 9 | <undefined>",
    "| 6 | 7 | 8 | 9 | <undefined>",
    "| 7 | 8 | 9 | <undefined>",
    "| 8 | 9 | <undefined>",
    "| 9 | <undefined>",
    "| <undefined>",
    "| 	symbol-token",
    "element",
    "list_car_element",
    "token",
    "| 	lisp-char",
    "whitespace",
    "backspace",
    "#\b",
    "#\b",
    "|  	tab |  	newline |  	linefeed |  	page |  	return-char |  	space",
    "tab",
    "#\t",
    "#\t",
    "|  	newline |  	linefeed |  	page |  	return-char |  	space",
    "newline",
    "#\r",
    "#\r",
    "|  	linefeed |  	page |  	return-char |  	space",
    "linefeed",
    "#\n",
    "#\n",
    "|  	page |  	return-char |  	space",
    "page",
    "|  	return-char |  	space",
    "return-char",
    "#\r",
    "#\r",
    "|  	space",
    "#\\space ",
    "#\\space",
    "|  	constituent-char | 	single-escape |  	multiple-escape | 	macro-char",
    "constituent-char",
    "| % | & | * | + | - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| & | * | + | - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| * | + | - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| + | - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| - | . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| . | / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| / | 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 3 | 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 4 | 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 5 | 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 6 | 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 7 | 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 8 | 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 9 | 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 	: | < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| < | = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| = | > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| > | @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| @ |  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "|  	A | B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| B | C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| C | D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| D | E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| E | F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| F | G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| G | H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| H | I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| I | J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| J | K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| K | L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| L | M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| M |  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "|  	N | O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| O | P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| P | Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| Q | R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| R | S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| S | T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| T | U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| U | V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| V | W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| W | X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| X | Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| Y | Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| Z | 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| 	a | b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| b | c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| c | d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| d | e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| e | f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| f | g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| g | h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| h | i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| i | j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| j | k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| k | l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| l | m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| m |  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "|  	n | o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| o | p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| p | q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| q | r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| r | s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| s | t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| t | u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| u | v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| v | w | x | y | z |	 	^ | _ | ~ | rubout",
    "| w | x | y | z |	 	^ | _ | ~ | rubout",
    "| x | y | z |	 	^ | _ | ~ | rubout",
    "| y | z |	 	^ | _ | ~ | rubout",
    "| z |	 	^ | _ | ~ | rubout",
    "|	 	^ | _ | ~ | rubout",
    "| _ | ~ | rubout",
    "| ~ | rubout",
    "| rubout",
    "#\rubout",
    "#\rubout",
    "| 	single-escape |  	multiple-escape | 	macro-char",
    "single-escape",
    "#\backslash",
    "#\backslash",
    "|  	multiple-escape | 	macro-char",
    "multiple-escape",
    "#\vertical-bar",
    "#\vertical-bar",
    "| 	macro-char",
    "terminating-char",
    "| ' | left-parent | right-parent | , | ; | `",
    "| left-parent | right-parent | , | ; | `",
    "| right-parent | , | ; | `",
    "| , | ; | `",
    "| ; | `",
    "| `",
    "|  	non-terminating-char",
    "##  left-parent := #\() right-parent := #\\)",
    "  left-parent := #\() right-parent := #\\)",
    "| 	array | 	sequence | 	type | 	input-stream | 	output-stream | 	class",
    "| 	sequence | 	type | 	input-stream | 	output-stream | 	class",
    "| 	type | 	input-stream | 	output-stream | 	class",
    "| 	input-stream | 	output-stream | 	class",
    "| 	output-stream | 	class",
    "| 	class",
    "| 	<undefined>",
    " LIST { object }* )",
    "( CAR list )",
    " CAR list )",
    " CDR list )",
    "	( + {number-token}* ) 	",
    " + {number-token}* )",
    " {number-token}* )",
    "number-token",
    " )",
    "	( < {number-token}* ) 	",
    " < {number-token}* )",
    " {number-token}* )",
    "number-token",
    " )",
    "	( <= {number-token}* ) 		",
    " <= {number-token}* )",
    "	( > {number-token}* ) 			",
    " > {number-token}* )",
    " {number-token}* )",
    "number-token",
    " )",
    "	( >= {number-token}* )		 		",
    " >= {number-token}* )",
    "( /= {number-token}* )",
    " /= {number-token}* )",
    "| 	( != {number-token}* )",
    " != {number-token}* )",
    "( EQ object object )",
    " EQ object object )",
    "(EQL object object )",
    "| 	car | 	cdr | 	cons | 	eq | 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "| 	cdr | 	cons | 	eq | 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "| 	cons | 	eq | 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    " CONS object object )",
    "| 	eq | 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "| 	if | 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    " IF test-form then-form [else-form] )",
    "| 	return | 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    " RETURN [form] )",
    "| 	block | 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    " BLOCK block-name { form }* )",
    "| 	( SETQ {setq-pair}* ) | 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    " SETQ {setq-pair}* )",
    "| 	num-add | 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-add",
    "| 	num-less-than | 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-less-than",
    "| 	num-less-or-equal-than | 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-less-or-equal-than",
    "| 	num-greater-than | 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-greater-than",
    "| 	num-greater-or-equal-than | 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-greater-or-equal-than",
    "| 	num-equal-than  | 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-equal-than",
    " = {number-token}* )",
    " {number-token}* )",
    "number-token",
    " )",
    "| 	num-not-equal-than | 	( LOOP {compound-form}* )",
    "num-not-equal-than",
    "| 	( LOOP {compound-form}* )",
    " LOOP {compound-form}* )",
    " SETQ {setq-pair}* )",
    " DEFCONSTANT name form [documentation] )",
    " IF test-form then-form [else-form] )",
    " RETURN [form] )",
    " LOOP {compound-form}* )",
    " DEFUN function-name lambda-list [documentation] {form}* )",
    " DEFSTRUCT name ( {slot-name}* ) )",
    " name lambda-list [documentation] {form}* )",
    "name",
    "symbol-token",
    " lambda-list [documentation] {form}* )",
    "lambda-list",
    "( {var}* )",
    " {var}* )",
    "var",
    "symbol-token",
    " )",
    " [documentation] {form}* )",
    " {form}* )",
    "form",
    "object | symbol-token | compound-form",
    "object",
    "| symbol-token | compound-form",
    "symbol-token",
    "| compound-form",
    " )",
    "form",
    "object | symbol-token | compound-form",
    "object",
    "| symbol-token | compound-form",
    "symbol-token",
    "| compound-form",
    " )",

    /* TODO
     */
    "#\\b",
    "#\\b",
    "#\\t",
    "#\\t",
    "#\\r",
    "#\\r",
    "#\\n",
    "#\\n",
    "#\\p",
    "#\\p",
    "#\\r",
    "#\\r",
    "#\\space ",
    "#\\space",
    "#\\rubout",
    "#\\rubout",
    "#\\backslash",
    "#\\backslash",
    "#\\vertical-bar",
    "#\\vertical-bar",
    "##  left-parent := #\\() right-parent := #\\)",
    "  left-parent := #\\() right-parent := #\\)",


    /* syntax object key
     */
    "left-parent ::=",
    "right-parent ::=",
    "##left-parent ::=",
    ":= ::=",
    "#\()right-parent ::=",
    ":= ::=",
    "#\\) ::=",
    "sign ::=",
    "decimal-digit ::=",
    "decimal-point ::=",
    "sign ::=",
    "digit ::=",
    "sign ::=",
    "digit ::=",
    "slash ::=",
    "digit ::=",
    "sign ::=",
    "decimal-digit ::=",
    "decimal-point ::=",
    "decimal-digit ::=",
    "exponent ::=",
    "sign ::=",
    "decimal-digit ::=",
    "decimal-point ::=",
    "decimal-digit ::=",
    "exponent ::=",
    "exponent-marker ::=",
    "sign ::=",
    "digit ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "LIST ::=",
    "object ::=",
    "<undefined> ::=",
    "array ::=",
    "sequence ::=",
    "type ::=",
    "input-stream ::=",
    "output-stream ::=",
    "class ::=",
    "CONS ::=",
    "object ::=",
    "object ::=",
    "CAR ::=",
    "list ::=",
    "CDR ::=",
    "list ::=",
    "SETQ ::=",
    "setq-pair ::=",
    "setq-var ::=",
    "form ::=",
    "DEFCONSTANT ::=",
    "name ::=",
    "form ::=",
    "documentation ::=",
    "SETQ ::=",
    "setq-pair ::=",
    "LOOP ::=",
    "compound-form ::=",
    "lambda-expression ::=",
    "CAR ::=",
    "CDR ::=",
    "CONS ::=",
    "<TBD> ::=",
    "QUOTE ::=",
    "LET ::=",
    "LET* ::=",
    "IF ::=",
    "BLOCK ::=",
    "CATCH ::=",
    "THROW ::=",
    "SETQ ::=",
    "<TBD> ::=",
    "<TBD> ::=",
    "<TBD> ::=",
    "IF ::=",
    "test-form ::=",
    "then-form ::=",
    "else-form ::=",
    "EQ ::=",
    "object ::=",
    "object ::=",
    "(EQL ::=",
    "object ::=",
    "object ::=",
    "(EQUAL ::=",
    "object ::=",
    "object ::=",
    "LOOP ::=",
    "compound-form ::=",
    "RETURN ::=",
    "form ::=",
    "BLOCK ::=",
    "block-name ::=",
    "form ::=",
    "DEFUN ::=",
    "function-name ::=",
    "lambda-list ::=",
    "documentation ::=",
    "form ::=",
    "var ::=",
    "<TBD> ::=",
    "LET ::=",
    "(var ::=",
    "(var ::=",
    "init-form)) ::=",
    "declaration ::=",
    "form ::=",
    "number-token ::=",
    "number-token ::=",
    "<= ::=",
    "number-token ::=",
    "number-token ::=",
    ">= ::=",
    "number-token ::=",
    "number-token ::=",
    "/= ::=",
    "number-token ::=",
    "!= ::=",
    "number-token ::=",
    "DEFSTRUCT ::=",
    "name ::=",
    "slot-name ::=",
    "name ::=",
    "lambda-list ::=",
    "documentation ::=",
    "form ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "slash ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "slash ::=",
    "<undefined> ::=",
    "decimal-point ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "decimal-point ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "decimal-point ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "decimal-point ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "exponent-marker ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "<undefined> ::=",
    "object ::=",
    "left-parent ::=",
    "right-parent ::=",
    "left-parent ::=",
    "array ::=",
    "sequence ::=",
    "type ::=",
    "input-stream ::=",
    "output-stream ::=",
    "class ::=",
    "<undefined> ::=",
    "list ::=",
    "LIST ::=",
    "car ::=",
    "CAR ::=",
    "cdr ::=",
    "CDR ::=",
    "num-add ::=",
    "num-less-than ::=",
    "num-less-or-equal-than ::=",
    "<= ::=",
    "num-greater-than ::=",
    "num-greater-or-equal-than ::=",
    ">= ::=",
    "num-euqal-than ::=",
    "num-not-equal-than ::=",
    "/= ::=",
    "!= ::=",
    "eq ::=",
    "EQ ::=",
    "eql ::=",
    "(EQL ::=",
    "equal ::=",
    "(EQUAL ::=",
    "compound-form ::=",
    "CONS ::=",
    "IF ::=",
    "RETURN ::=",
    "BLOCK ::=",
    "SETQ ::=",
    "LOOP ::=",
    "setq ::=",
    "SETQ ::=",
    "defconstant ::=",
    "DEFCONSTANT ::=",
    "if ::=",
    "IF ::=",
    "return ::=",
    "RETURN ::=",
    "loop ::=",
    "LOOP ::=",
    "defun ::=",
    "DEFUN ::=",
    "defstruct ::=",
    "DEFSTRUCT ::=",
    "defmacro ::=",
    "name ::=",
    "lambda-list ::=",
    "<TBD> ::=",
    
    
};


const char*
rule_match_element(char *name, int len)
{
    int cnt = ARR_LEN(LANG_ELEMENTS);

    for (int i = 0; i < cnt; i++) {

	if (strlen(LANG_ELEMENTS[i]) == len) {
	    
	    if (!memcmp(LANG_ELEMENTS[i], name, len)) {

		return LANG_ELEMENTS[i];
	    }
	}
    }

    return NULL;
}


